---
title: Providence Seed Library
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'Providence Seed Library is a public seed library  offering free open-pollinated,
  heirloom, culturally  relevant, and indigenous seeds. The collections are  housed
  at Providence Community Library and Providence  Public Library branches.

'
baseurl: 
url: http://provseedlib.com
twitter_username: jekyllrb
github_username: jekyll
Site Logo: "/uploads/Seed-Library-Stickers_V2.png"
