<<<<<<< Updated upstream
---
title: Your awesome title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
=======
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Providence Seed Library
description: > # this means to ignore newlines until "baseurl:"
  Providence Seed Library is a public seed library 
  offering free open-pollinated, heirloom, culturally 
  relevant, and indigenous seeds. The collections are 
  housed at Providence Community Library and Providence 
  Public Library branches.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://provseedlib.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
>>>>>>> Stashed changes

'
baseurl: 
url: http://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
