---
title: Providence Seed Library
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'Providence Seed Library is a public seed library  offering free open-pollinated,
  heirloom, culturally  relevant, and indigenous seeds. The collections are located
  at branches of the Community Libraries of Providence.

'
baseurl: 
url: http://provseedlib.com
twitter_username: jekyllrb
github_username: jekyll
Site Logo: "/uploads/Seed-Library-Stickers_V2.png"
Banner Color: "#e8483c"
Background Color: "#000"
Accent Color 1: "#ffe22b"
Accent Color 2: "#00c4bb"
Accent Color 3: "#5151bf"
